/**
 * QueueItem entity — represents a pending or in-flight work item in the plan queue.
 *
 * Queue items originate from plan files dropped into `session-plans/pending/*.md`
 * and are processed by the QueueService (Task 1.8).
 *
 * The state enum is derived from the state-machine needs of the queue processor:
 * - `Pending`     → item is waiting to be dispatched
 * - `Active`      → a session is executing this item right now
 * - `Completed`   → session finished successfully
 * - `Failed`      → session failed; item eligible for retry (up to max retries)
 * - `Paused`      → dispatcher was paused; item will resume when dispatcher restarts
 * - `Quarantined` → max retries exceeded; item will not be retried automatically
 */

/** All possible states for a queue item. */
export const QueueItemState = {
  Pending: 'Pending',
  Active: 'Active',
  Completed: 'Completed',
  Failed: 'Failed',
  Paused: 'Paused',
  Quarantined: 'Quarantined',
} as const;

export type QueueItemState =
  (typeof QueueItemState)[keyof typeof QueueItemState];

/**
 * All valid state transitions for a QueueItem.
 *
 * Used by the queue service to validate state changes before persisting them.
 * Keeping this table in the entity file ensures the state machine and storage
 * always agree on what is allowed.
 *
 * Mapping: fromState → Set of valid toStates
 */
export const QUEUE_ITEM_TRANSITIONS: Readonly<
  Record<QueueItemState, ReadonlyArray<QueueItemState>>
> = {
  [QueueItemState.Pending]: [QueueItemState.Active, QueueItemState.Paused],
  [QueueItemState.Active]: [
    QueueItemState.Completed,
    QueueItemState.Failed,
    QueueItemState.Paused,
  ],
  [QueueItemState.Failed]: [
    QueueItemState.Pending, // retry
    QueueItemState.Quarantined, // max retries exceeded
  ],
  [QueueItemState.Paused]: [
    QueueItemState.Pending, // resume
  ],
  [QueueItemState.Completed]: [], // terminal
  [QueueItemState.Quarantined]: [], // terminal
};

/**
 * QueueItem entity — the canonical shape of a queue record.
 *
 * Note: task payloads are stored as a generic record so that the domain layer
 * stays agnostic of plan-file specifics. The queue module parses the YAML
 * frontmatter from plan files and stores structured fields here.
 */
export interface QueueItem {
  /** Unique item identifier (generated by the store). */
  id: string;

  /**
   * Session key of the project that owns this item.
   *
   * Format: `{projectId}:{sessionType}:{threadId}` — built by sessionKey() helper.
   */
  sessionKey: string;

  /** Current lifecycle state. */
  state: QueueItemState;

  /**
   * Numeric dispatch priority — higher value = higher priority.
   *
   * Sourced from `priority:` YAML frontmatter in the plan file (default 0).
   */
  priority: number;

  /**
   * Dedup key used to prevent double-enqueue of the same plan file.
   *
   * Computed as `{filePath}:{mtime}` by the file-watcher (Task 1.8).
   */
  dedupKey: string;

  /**
   * Structured payload from the plan file (frontmatter + resolved paths).
   *
   * Opaque at the domain layer — parsed and typed by the queue module.
   */
  payload: Record<string, unknown>;

  /** Number of times this item has been attempted (incremented on each dispatch). */
  attempts: number;

  /** Maximum allowed attempts before the item is quarantined. */
  maxAttempts: number;

  /** When the item was added to the queue. */
  createdAt: Date;

  /** When the item was last modified (state change, retry, etc.). */
  updatedAt: Date;

  /** When this item transitioned into `Active` state (null otherwise). */
  startedAt?: Date;

  /** When this item reached a terminal state (Completed or Quarantined). */
  endedAt?: Date;
}

/** Shape required to create a new QueueItem (store-generated fields excluded). */
export interface QueueItemDraft {
  sessionKey: string;
  priority?: number;
  dedupKey: string;
  payload?: Record<string, unknown>;
  maxAttempts?: number;
}

/**
 * Returns true if the given state is terminal (no further transitions allowed).
 */
export function isQueueItemTerminal(state: QueueItemState): boolean {
  return QUEUE_ITEM_TRANSITIONS[state].length === 0;
}

/**
 * Returns true if `toState` is a valid transition from `fromState`.
 */
export function isValidQueueItemTransition(
  fromState: QueueItemState,
  toState: QueueItemState,
): boolean {
  return (QUEUE_ITEM_TRANSITIONS[fromState] as QueueItemState[]).includes(
    toState,
  );
}
