/**
 * Session entity — represents a running or completed Claude Code worker session.
 *
 * Sessions are the central unit of work in Orch. They are created when the
 * SessionManager dispatches a QueueItem, and transition through the state machine
 * as Claude Code hook events arrive at POST /hooks/:event.
 *
 * State machine transitions (derived from Claude-Code-Agent-Monitor.md §3-4):
 *
 *   Idle ──► Starting ──► Running ──► Stopping ──► Ended   (normal path)
 *                 │                      │
 *                 └──► Failed            ├──► RateLimited
 *                                        └──► Failed
 *
 * Key invariant: ONLY `SessionEnd` hook drives a session to `Ended`.
 *                `Stop` merely signals turn-end; session remains resumable.
 */

/** All valid session states. */
export const SessionState = {
  /** Session has been created but spawning has not started. */
  Idle: 'Idle',
  /** ccs subprocess is starting; waiting for first hook event. */
  Starting: 'Starting',
  /** Claude Code is actively processing; hook events are arriving. */
  Running: 'Running',
  /** User pressed Esc / sent Ctrl-C; turn ended but session is resumable. */
  Stopping: 'Stopping',
  /**
   * Graceful session-end in progress (Task 3.3).
   *
   * Entered when `session.forceHandoff` fires and `profile.autoHandoff = true`.
   * SessionManager has written the slash-command to stdin and is waiting up to
   * `gracefulEndTimeoutMs` for the SessionEnd hook to fire.
   *
   * Valid transitions out: → Ended (hook fired), → Failed (SIGKILL after timeout).
   *
   * I-11: every transition to/from Ending emits a log entry + OTEL span event.
   */
  Ending: 'Ending',
  /** Session process exited cleanly (terminal). */
  Ended: 'Ended',
  /** Subprocess crashed or watchdog hard-killed it (terminal). */
  Failed: 'Failed',
  /** API rate-limit detected; awaiting ccs failover / retry. */
  RateLimited: 'RateLimited',
  /** Token budget exhausted; handoff builder will be triggered. */
  ContextFull: 'ContextFull',
} as const;

export type SessionState = (typeof SessionState)[keyof typeof SessionState];

/** Terminal states — no further hook events expected. */
export const SESSION_TERMINAL_STATES: ReadonlySet<SessionState> = new Set([
  SessionState.Ended,
  SessionState.Failed,
]);

/**
 * Session entity — the canonical shape of a session record.
 */
export interface Session {
  /** Orch-internal unique identifier (UUID generated by the store). */
  id: string;

  /**
   * Registry-assigned project identifier.
   *
   * Must be a URL-safe lowercase identifier; no project-specific values hardcoded (I-2).
   */
  projectId: string;

  /**
   * Branded session key (`{projectId}:{sessionType}:{threadId}`).
   *
   * Used as the in-process Promise-chain lock key (D3).
   */
  sessionKey: string;

  /** Current lifecycle state. */
  state: SessionState;

  /** Model identifier reported by Claude Code (populated after SessionStart hook). */
  model?: string;

  /** Claude Code's own session ID (from the SessionStart hook payload). */
  claudeSessionId?: string;

  /**
   * Total tokens consumed so far (updated on compaction / budget-check events).
   *
   * Nullable until the first token-count event arrives.
   */
  tokensUsed?: number;

  /**
   * Reason the session ended — populated when transitioning to Ended or Failed.
   *
   * Examples: "user_cancel", "context_full", "rate_limit", "process_exit"
   */
  endReason?: string;

  /** When the session record was created (Idle state entry). */
  createdAt: Date;

  /** When the session last changed state. */
  updatedAt: Date;

  /** When the subprocess was successfully spawned (Starting → Running). */
  startedAt?: Date;

  /** When the session reached a terminal state (Ended or Failed). */
  endedAt?: Date;

  /**
   * Absolute path to the git worktree created for this session (Phase 6.3).
   *
   * Set when `SpawnConfig.worktreeIsolation` is true and the adapter successfully
   * creates the worktree. Cleared (null) when the session terminates so the sweep
   * hook (6.3.5) knows the path has been pruned.
   *
   * `null` represents explicit cleanup (worktree pruned); `undefined` means the
   * field has not been set (worktree isolation was not used for this session).
   */
  worktreePath?: string | null;
}

/** Shape required to create a new Session record (store-generated fields excluded). */
export interface SessionDraft {
  projectId: string;
  sessionKey: string;
  model?: string;
}

/**
 * Returns true if the session state is terminal (no further transitions expected).
 */
export function isSessionTerminal(state: SessionState): boolean {
  return SESSION_TERMINAL_STATES.has(state);
}

// ── SessionManager input/output types ─────────────────────────────────────────

/**
 * Plan passed to `SessionManager.runSession()`.
 *
 * Minimal — carries only what the orchestrator needs to spawn or resume a
 * Claude Code worker. Profile configuration lives in `.orch/profile.yaml`
 * (loaded by the project registry, not duplicated here).
 *
 * I-2: no project-specific fields.
 */
export interface SessionPlan {
  /** Registry project identifier. */
  projectId: string;

  /** The prompt to send to Claude Code. */
  prompt: string;

  /** ccs profile name (maps to a Claude Code account). Defaults to 'default'. */
  profile: string;

  /**
   * If set, resume an existing Claude Code session instead of spawning fresh.
   * Format expected by ClaudeCodeAdapter.resume(): `{profile}/{claudeSessionId}`.
   */
  resumeSessionId?: string;

  /** Working directory for the spawned process; defaults to process.cwd(). */
  workdir?: string;

  /**
   * Optional handoff seed prompt prepended to `prompt` for context continuity.
   *
   * Set by HandoffOrchestratorService (Task 3.6) when spawning the successor session
   * after a CONTEXT_FULL termination. Carries the RenderedPrompt.text from the
   * previous session's HandoffContextBuilder.render() output.
   *
   * I-1: pure text — no LLM call involved in generating this value.
   */
  seedPrompt?: string;
}

/**
 * Result returned by `SessionManager.runSession()` after the session ends.
 */
export interface SessionResult {
  /** Orch-internal session ID (DB record). */
  sessionId: string;

  /**
   * Terminal status of the session.
   * - `ended`      : normal clean exit
   * - `rate-limited`: session was stopped by a rate-limit signal
   * - `context-full`: token budget exhausted
   * - `failed`     : unexpected error
   * - `cancelled`  : caller invoked cancelSession() / terminate()
   */
  status: 'ended' | 'rate-limited' | 'context-full' | 'failed' | 'cancelled';

  /** Process exit code from ccs / claude CLI, if available. */
  exitCode?: number;

  /** Error instance when status is 'failed'. */
  error?: Error;
}

/**
 * In-process view of an active session — returned by `getActiveSessions()`.
 *
 * Subset of full Session entity with the fields that are reliably set for a
 * running session plus the runtime handle reference (not persisted).
 */
export interface ActiveSession {
  /** Orch-internal session ID. */
  id: string;

  /** Registry project identifier. */
  projectId: string;

  /** Per-session FIFO lock key. */
  sessionKey: string;

  /** When the subprocess was spawned (epoch ms). */
  startedAt: number;

  /**
   * Last heartbeat timestamp (epoch ms).
   * Null if no hook event has been received yet.
   */
  lastHeartbeatAt: number | null;
}
